#SUGGESTION: PLEASE USE ABSOLUTE PATH
export DARKNET=<PATH_TO_DARKNET>
export PRJ_PATH=<PATH_TO_YOLOV3-DATALOADER>

cd $DARKNET
./darknet detector demo \
$PRJ_PATH/<NEW_MODEL>.data \
$PRJ_PATH/<NEW_MODEL>.cfg \
$PRJ_PATH/<YOUR_FINAL_WEIGHT_FROM_COLAB> \
-c 0 -thresh .5
